# Generated by Django 2.2.17 on 2021-04-20 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='newsStory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=50)),
                ('public_date', models.DateTimeField()),
                ('story_text', models.CharField(max_length=600)),
            ],
        ),
    ]
